spring.datasource.url=jdbc:mysql://curd-javawebappdb.mysql.database.azure.com:3306/crud_db?useSSL=true
spring.datasource.username=adminuser
spring.datasource.password=55667788@Cws

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
