deploy:
  runs-on: ubuntu-latest
  needs: build

  permissions:
    id-token: write
    contents: read

  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: ./artifact

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50A3301342A9438E89C9BBB5527E0C24 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_317AB25ED62F442CBE29F72E29784BD9 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AF860FB8982348DDA5603EF857CFAA78 }}

    - name: Verify Azure Subscription
      run: |
        az account show --output table

    - name: Verify App Service
      run: |
        az webapp show \
          --name backend-java-webapp \
          --resource-group CURD_project_java

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: backend-java-webapp
        package: ./artifact/*.jar
